[project]
name = "subtensorapi"
authors = [
  { name="Opentensor Foundation", email="cameron@opentensor.ai" },
  { name="Opentensor Foundation", email="eduardo@opentensor.ai" },
]
license = { file = "LICENSE" }
description = "Subtensor API package for bittensor"
readme = "README.md"
dynamic = ["version"]

requires-python = ">=3.7"


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[console_scripts]
sync_and_save = "subtensorapi.cli:sync_and_save"
blockAtRegistration_for_all_and_save = "subtensorapi.cli:blockAtRegistration_for_all_and_save"
